# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "actanble/centos7"

  config.vm.network "forwarded_port", guest: 22, host: 20022
  config.vm.network "forwarded_port", guest: 5111, host: 25111
  config.vm.hostname = "vuls"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
      yum install -y yum-utils device-mapper-persistent-data lvm2 ;
      yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo ;
      yum makecache fast;
      yum -y install docker-ce-17.12.0.ce-1.el7.centos ;
      systemctl start docker ;
      mkdir -p /etc/docker
      cat > /etc/docker/daemon.json <<- EOF
      {
        "registry-mirrors": ["https://1n1i3zwf.mirror.aliyuncs.com"]
      }
      EOF
  SHELL

end
