# https://vuls.io/docs/en/usage-settings.html#servers-section
[servers]
[servers.testserver]
host = "127.0.0.1"
port = "22"
user = "root"
keyPath = "/root/.ssh/id_rsa"
scanMode = [ "fast-root" ]

[cveDict]
type = "mysql"
url = "root:vulspa55@tcp(10.0.11.36:3306)/vuls_cve?parseTime=true"

[ovalDict]
type = "mysql"
url = "root:vulspa55@tcp(10.0.11.36:3306)/vuls_goval?parseTime=true"

[gost]
type = "mysql"
url = "root:vulspa55@tcp(10.0.11.36:3306)/vuls_gost?parseTime=true"

[exploit]
type = "mysql"
url = "root:vulspa55@tcp(10.0.11.36:3306)/vuls_exploit?parseTime=true"

