version: '2'

services:
  vuls:
    image: vuls/vuls
    container_name: vuls
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./:/vuls
      - ./vuls-log:/var/log/vuls

  cve:
    image: vuls/go-cve-dictionary
    container_name: cve
    command: server --bind=0.0.0.0
    ports:
      - 1323:1323
    volumes:
      - ./:/vuls
      - ./vuls-log:/var/log/vuls

  oval:
    image: vuls/oval-dictionary
    container_name: oval
    command: server --bind=0.0.0.0
    ports:
      - 1324:1324
    volumes:
      - ./:/vuls
      - ./vuls-log:/var/log/vuls


  gost:
    image: vuls/gost
    container_name: gost
    command: server --bind=0.0.0.0
    ports:
      - 1325:1325
    volumes:
      - ./:/vuls
      - ./vuls-log:/var/log/vuls


  go-exploitdb:
    image: princechrismc/go-exploitdb
    container_name: exploitdb
    command: server --bind=0.0.0.0
    ports:
      - 1326:1326
    volumes:
    volumes:
      - ./:/vuls
      - ./vuls-log:/var/log/vuls


  mysql:
    container_name: vuls_db
    image: 'registry.cn-hangzhou.aliyuncs.com/xxzhang/mysql:5.7'
    volumes:
      - /srv/docker/mysql/vuls_data:/var/lib/mysql
      - ./docs/mysql.conf.d:/etc/mysql/mysql.conf.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=vuls
      - MYSQL_PASSWORD=xxvulspa55xx
      - MYSQL_DATABASE=default_db
      - MYSQL_ROOT_PASSWORD=vulspa55
    networks:
      customize_net:
        ipv4_address: 10.0.11.101


  vulsrepo:
    image: vuls/vulsrepo
    volumes:
      - ./results:/vuls/results/
      - ./:/vuls
      - ./vuls-log:/var/log/vuls
    ports:
      - "5111:5111"
    networks:
      customize_net:
        ipv4_address: 10.0.11.51

networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24
